# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'turtlebot_gui.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(836, 662)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.btn_login = QPushButton(self.page)
        self.btn_login.setObjectName(u"btn_login")
        self.btn_login.setGeometry(QRect(510, 240, 91, 91))
        self.id_input_line = QLineEdit(self.page)
        self.id_input_line.setObjectName(u"id_input_line")
        self.id_input_line.setGeometry(QRect(290, 244, 201, 41))
        font = QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        self.id_input_line.setFont(font)
        self.pw_input_line = QLineEdit(self.page)
        self.pw_input_line.setObjectName(u"pw_input_line")
        self.pw_input_line.setGeometry(QRect(290, 290, 201, 41))
        self.pw_input_line.setFont(font)
        self.pw_input_line.setEchoMode(QLineEdit.EchoMode.Password)
        self.id_lbl = QLabel(self.page)
        self.id_lbl.setObjectName(u"id_lbl")
        self.id_lbl.setGeometry(QRect(170, 260, 131, 16))
        self.id_lbl.setFont(font)
        self.pw_lbl = QLabel(self.page)
        self.pw_lbl.setObjectName(u"pw_lbl")
        self.pw_lbl.setGeometry(QRect(170, 300, 121, 17))
        self.pw_lbl.setFont(font)
        self.ex_lbl = QLabel(self.page)
        self.ex_lbl.setObjectName(u"ex_lbl")
        self.ex_lbl.setGeometry(QRect(300, 330, 151, 51))
        self.stackedWidget.addWidget(self.page)
        self.stackedWidgetPage1 = QWidget()
        self.stackedWidgetPage1.setObjectName(u"stackedWidgetPage1")
        self.btn_menu_toggle = QPushButton(self.stackedWidgetPage1)
        self.btn_menu_toggle.setObjectName(u"btn_menu_toggle")
        self.btn_menu_toggle.setGeometry(QRect(670, 30, 121, 121))
        self.groupBox = QGroupBox(self.stackedWidgetPage1)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(380, 180, 411, 411))
        self.btn_forward = QPushButton(self.groupBox)
        self.btn_forward.setObjectName(u"btn_forward")
        self.btn_forward.setGeometry(QRect(150, 20, 111, 111))
        self.btn_left = QPushButton(self.groupBox)
        self.btn_left.setObjectName(u"btn_left")
        self.btn_left.setGeometry(QRect(20, 150, 111, 111))
        self.btn_right = QPushButton(self.groupBox)
        self.btn_right.setObjectName(u"btn_right")
        self.btn_right.setGeometry(QRect(280, 150, 111, 111))
        self.btn_stop = QPushButton(self.groupBox)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setGeometry(QRect(150, 150, 111, 111))
        self.btn_backward = QPushButton(self.groupBox)
        self.btn_backward.setObjectName(u"btn_backward")
        self.btn_backward.setGeometry(QRect(150, 280, 111, 111))
        self.velocity_label = QLabel(self.groupBox)
        self.velocity_label.setObjectName(u"velocity_label")
        self.velocity_label.setGeometry(QRect(30, 40, 67, 17))
        self.angular_labe = QLabel(self.groupBox)
        self.angular_labe.setObjectName(u"angular_labe")
        self.angular_labe.setGeometry(QRect(30, 80, 67, 17))
        self.btn_nav_start = QPushButton(self.stackedWidgetPage1)
        self.btn_nav_start.setObjectName(u"btn_nav_start")
        self.btn_nav_start.setGeometry(QRect(30, 110, 71, 51))
        self.x_label = QLabel(self.stackedWidgetPage1)
        self.x_label.setObjectName(u"x_label")
        self.x_label.setGeometry(QRect(390, 70, 101, 31))
        self.x_label.setFont(font)
        self.mode_label = QLabel(self.stackedWidgetPage1)
        self.mode_label.setObjectName(u"mode_label")
        self.mode_label.setGeometry(QRect(390, 20, 241, 31))
        self.mode_label.setFont(font)
        self.y_label = QLabel(self.stackedWidgetPage1)
        self.y_label.setObjectName(u"y_label")
        self.y_label.setGeometry(QRect(490, 70, 141, 31))
        self.y_label.setFont(font)
        self.distance_label = QLabel(self.stackedWidgetPage1)
        self.distance_label.setObjectName(u"distance_label")
        self.distance_label.setGeometry(QRect(390, 120, 131, 31))
        self.distance_label.setFont(font)
        self.log_list = QListWidget(self.stackedWidgetPage1)
        self.log_list.setObjectName(u"log_list")
        self.log_list.setGeometry(QRect(30, 170, 311, 421))
        self.btn_log_clear = QPushButton(self.stackedWidgetPage1)
        self.btn_log_clear.setObjectName(u"btn_log_clear")
        self.btn_log_clear.setGeometry(QRect(250, 130, 91, 31))
        self.btn_nav_stop = QPushButton(self.stackedWidgetPage1)
        self.btn_nav_stop.setObjectName(u"btn_nav_stop")
        self.btn_nav_stop.setGeometry(QRect(120, 110, 71, 51))
        self.groupBox_2 = QGroupBox(self.stackedWidgetPage1)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(30, 10, 161, 91))
        self.x_line = QLineEdit(self.groupBox_2)
        self.x_line.setObjectName(u"x_line")
        self.x_line.setGeometry(QRect(60, 10, 91, 31))
        self.y_line = QLineEdit(self.groupBox_2)
        self.y_line.setObjectName(u"y_line")
        self.y_line.setGeometry(QRect(60, 50, 91, 31))
        self.goal_x_lbl = QLabel(self.groupBox_2)
        self.goal_x_lbl.setObjectName(u"goal_x_lbl")
        self.goal_x_lbl.setGeometry(QRect(10, 20, 67, 17))
        self.goal_y_lbl = QLabel(self.groupBox_2)
        self.goal_y_lbl.setObjectName(u"goal_y_lbl")
        self.goal_y_lbl.setGeometry(QRect(10, 60, 67, 17))
        self.goal_x_label = QLabel(self.stackedWidgetPage1)
        self.goal_x_label.setObjectName(u"goal_x_label")
        self.goal_x_label.setGeometry(QRect(200, 30, 181, 17))
        self.goal_x_label.setFont(font)
        self.goal_y_label = QLabel(self.stackedWidgetPage1)
        self.goal_y_label.setObjectName(u"goal_y_label")
        self.goal_y_label.setGeometry(QRect(200, 80, 181, 17))
        self.goal_y_label.setFont(font)
        self.btn_exit_1 = QPushButton(self.stackedWidgetPage1)
        self.btn_exit_1.setObjectName(u"btn_exit_1")
        self.btn_exit_1.setGeometry(QRect(790, 0, 21, 21))
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QWidget()
        self.stackedWidgetPage2.setObjectName(u"stackedWidgetPage2")
        self.map_label = QLabel(self.stackedWidgetPage2)
        self.map_label.setObjectName(u"map_label")
        self.map_label.setGeometry(QRect(70, 20, 671, 581))
        self.map_label.setPixmap(QPixmap(u":/newPrefix/philip-myrtorp-AkOr2UkiqGE-unsplash.jpg"))
        self.btn_exit_2 = QPushButton(self.stackedWidgetPage2)
        self.btn_exit_2.setObjectName(u"btn_exit_2")
        self.btn_exit_2.setGeometry(QRect(790, 0, 21, 21))
        self.stackedWidget.addWidget(self.stackedWidgetPage2)

        self.verticalLayout.addWidget(self.stackedWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 836, 27))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_login.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.id_lbl.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.pw_lbl.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.ex_lbl.setText(QCoreApplication.translate("MainWindow", u"ex) admin/1234", None))
        self.btn_menu_toggle.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.groupBox.setTitle("")
        self.btn_forward.setText(QCoreApplication.translate("MainWindow", u"Go", None))
        self.btn_left.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.btn_right.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.btn_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_backward.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.velocity_label.setText(QCoreApplication.translate("MainWindow", u"Vel:  ", None))
        self.angular_labe.setText(QCoreApplication.translate("MainWindow", u"Ang: ", None))
        self.btn_nav_start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.x_label.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.mode_label.setText(QCoreApplication.translate("MainWindow", u"Mode: ", None))
        self.y_label.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.distance_label.setText(QCoreApplication.translate("MainWindow", u"Dis:", None))
        self.btn_log_clear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.btn_nav_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.groupBox_2.setTitle("")
        self.goal_x_lbl.setText(QCoreApplication.translate("MainWindow", u"Goal X:", None))
        self.goal_y_lbl.setText(QCoreApplication.translate("MainWindow", u"Goal Y:", None))
        self.goal_x_label.setText(QCoreApplication.translate("MainWindow", u"Goal X:", None))
        self.goal_y_label.setText(QCoreApplication.translate("MainWindow", u"Goal Y:", None))
        self.btn_exit_1.setText(QCoreApplication.translate("MainWindow", u"\u274c", None))
        self.map_label.setText("")
        self.btn_exit_2.setText(QCoreApplication.translate("MainWindow", u"\u274c", None))
    # retranslateUi

